version: '3.8'

include:
  - compose-database.yaml

services:
  symfony:
    image: vinderzz/symfony
    ports:
      - "80:8000"
    volumes:
      - ./api:/var/www/html

  composer:
    image: alexandrealrd/composer
    volumes:
      - ./docker/composer:/var/www/html/composer
    command: [ "composer", "install", "--no-interaction", "--prefer-dist", "--optimize-autoloader" ]

  adminer:
    image: alexandrealrd/adminer
    ports:
      - '8080:8080'