version: '3.7'

services:
  symfony:
    image: vinderzz/symfony
    ports:
      - "80:8000"
    volumes:
      - ./api:/var/www/html

  database:
    image: inesdabrat/postgresql-image
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: victor
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
    db_data: