version: '3.8'

services:
  database:
    image: inesdabrat/postgresql-image
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  composer:
    image: alexandrealrd/composer
    volumes:
      - ./docker/composer:/var/www/html/composer
    command: ["composer", "install", "--no-interaction", "--prefer-dist", "--optimize-autoloader"]

  adminer:
    image: alexandrealrd/adminer
    ports:
      - '8080:8080'

volumes:
  db_data: