version: '3.7'

services:
  symfony:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/symfony
    depends_on:
      - database

  database:
    image: postgres:12
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - database

  composer:
    image: composer:latest
    volumes:
      - .:/app
    command: composer install
    depends_on:
      - symfony

volumes:
  db_data: