version: '3.7'

services:
  symfony:
    build: ./docker/symfony
    volumes:
      - ./symfony-app:/var/www/symfony
    depends_on:
      - database

  database:
    build: ./docker/postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    build: ./docker/adminer
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  db_data: